### ISSUE TITLE
Suggestion use VIVID

### ISSUE THREAD

**Issue by robmachado** [wendtecnologia/dev4php#28]
Como uma sugestão alterar o box para a nova versão estável do Ubuntu, 15.04

config.vm.box = "ubuntu/vivid64", irá garantir maior tempo de "vida" para o pacote antes de ter uma nova atualização.

**Comment by walkeralencar** [comment]
Na verdade a 14.04 é uma LTS, e tem maior tempo de suporte, a próxima LTS virá na 16.04. Como segue abaixo, sendo assim, é mais plausível manter as LTS que são recomendadas para servidores, por utilizarem pacotes mais estáveis.

![image-release-cycle-large](https://cloud.githubusercontent.com/assets/459481/9020478/88db9b20-37e4-11e5-93f1-df065dbec987.png)

**Comment by robmachado** [comment]
Aprender é sempre bom 😀😀😀

Roberto
